"""Alembic migration environment configuration.

This file is auto-generated by Flask-Migrate and customized for MedAssist AI.
Run `flask db init` to generate the full Alembic structure.
"""

# This stub will be replaced when `flask db init` is run.
# For now it serves as a placeholder to indicate the migrations directory structure.
